export const users = [
  { userId: 1, userName: "khalil" },
  { userId: 2, userName: "oussema" },
];
export const msgs = [
  {
    msgId: 1,
    text: "hi oussema",
    photo: "khalil.jpg",
    userId: 1,
    currentUser: true,
  },
  {
    msgId: 2,
    text: "hi oussema thanks for your support you are such a generous man whhelped me when i were stuck",
    photo: "khalil.jpg",
    userId: 1,
    currentUser: true,
  },
  {
    msgId: 3,
    photo: "khalil.jpg",
    text: "hi khalil thanks",
    userId: 2,
    currentUser: false,
  },
  {
    msgId: 4,
    text: "that's all",
    photo: "khalil.jpg",
    userId: 1,
    currentUser: true,
  },
  {
    msgId: 5,
    text: "yes",
    photo: "khalil.jpg",
    userId: 2,
    currentUser: false,
  },
  {
    msgId: 6,
    text: "you are amazing take your time and learn correctly because its all about consistancy",
    photo: "khalil.jpg",
    userId: 2,
    currentUser: false,
  },
];
export const msgDesc = [
  {
    id: 1,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 2,
    sender: "oussema ben dahmen",
    lastMsg: "hi i am fine ",
    timeAgo: "2 days",
    numUnreadMsg: 2,
  },
  {
    id: 3,
    sender: "hichem lesmi",
    lastMsg: "hi",
    timeAgo: "2 weeks",
    numUnreadMsg: 1,
  },
  {
    id: 4,
    sender: "chiheb dridi",
    lastMsg: "how are your study...",
    timeAgo: "2 h",
    numUnreadMsg: 3,
  },
  {
    id: 5,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 6,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },

  {
    id: 7,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 8,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 9,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 10,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 11,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 12,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 13,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 14,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 15,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 16,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
  {
    id: 17,
    sender: "khalil ben mansour",
    lastMsg: "hello how are you...",
    timeAgo: "5 min",
    numUnreadMsg: 3,
  },
];
export const friendDesc = [
  {
    id: 1,
    friend: "Oussema Ben Dahmen",
    desc: "front end engineer",
  },
  {
    id: 2,
    friend: "khalil ben mansour",
    desc: "react developer",
  },
  {
    id: 3,
    friend: "marwen ben abdellatif",
    desc: "web developer engineer",
  },
  {
    id: 4,
    friend: "Fahd zaghdoudi",
    desc: "data scientist",
  },
  {
    id: 5,
    friend: "ibrahim saheb marwen",
    desc: "software engineer",
  },
  {
    id: 6,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 7,
    friend: "omar riabi",
    desc: "mobile engineer",
  },
  {
    id: 8,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 9,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 10,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 11,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 12,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 13,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 14,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 15,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
  {
    id: 16,
    friend: "khalil ben mansour",
    desc: "hello how are you...",
  },
];
